server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/kwon/Desktop/study/msa-ecommerce
          uri: https://github.com/dohyun-dev/msa-ecommerce.git
#          username: ""
#          password: ""