server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: quest
    passord: quest
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/kwon/Desktop/study/msa-ecommerce
          uri: https://github.com/dohyun-dev/msa-ecommerce.git
#          username: ""
#          password: ""
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
